/** Compact ad + tracker host lists for session request filter. */

export interface CompactBlocklist {
  version: 1
  ads: string[]
  trackers: string[]
  pathRules: string[]
}

export const COMPACT_BLOCKLIST: CompactBlocklist = {
  version: 1,
  ads: [
    'doubleclick.net',
    'googlesyndication.com',
    'googleadservices.com',
    'adservice.google.com',
    'pagead2.googlesyndication.com',
    'tpc.googlesyndication.com',
    'adnxs.com',
    'adsrvr.org',
    'advertising.com',
    'adform.net',
    'adcolony.com',
    'admob.com',
    'amazon-adsystem.com',
    'media.net',
    'outbrain.com',
    'taboola.com',
    'criteo.com',
    'criteo.net',
    'pubmatic.com',
    'rubiconproject.com',
    'openx.net',
    'casalemedia.com',
    'bidswitch.net',
    'smartadserver.com',
    'moatads.com',
    'yieldmo.com',
    'sharethrough.com',
    '3lift.com',
    'rlcdn.com',
    'exelator.com',
    'bluekai.com',
    'krxd.net',
    'quantserve.com',
    'scorecardresearch.com',
    '2mdn.net',
    'ads-twitter.com',
    'ads.linkedin.com',
    'an.facebook.com',
    'pixel.facebook.com'
  ],
  trackers: [
    'google-analytics.com',
    'googletagmanager.com',
    'google-analytics.co',
    'analytics.google.com',
    'hotjar.com',
    'static.hotjar.com',
    'script.hotjar.com',
    'segment.io',
    'segment.com',
    'cdn.segment.com',
    'api.segment.io',
    'mixpanel.com',
    'cdn.mxpnl.com',
    'amplitude.com',
    'api.amplitude.com',
    'cdn.amplitude.com',
    'fullstory.com',
    'rs.fullstory.com',
    'clarity.ms',
    'www.clarity.ms',
    'mouseflow.com',
    'heap-api.com',
    'heapanalytics.com',
    'newrelic.com',
    'nr-data.net',
    'bat.bing.com',
    'connect.facebook.net',
    'stats.g.doubleclick.net',
    'px.ads.linkedin.com',
    'snap.licdn.com',
    'static.ads-twitter.com',
    'analytics.tiktok.com',
    'analytics.twitter.com',
    'sentry.io',
    'browser.sentry-cdn.com',
    'log.pinterest.com',
    'tr.pinterest.com'
  ],
  pathRules: ['facebook.com/tr', 'facebook.com/tr/', 'www.facebook.com/tr']
}
